/**
* @author JHafer
* @date 20180402
* @version 1.00
* @description CommunitiesSelfRegConfirmControllerTest - Test class for the CommunitiesSelfRegConfirmController class
*/
@isTest
global with sharing class CommunitiesSelfRegConfirmControllerTest {

    /**
    * @description testCommunitiesSelfRegConfirmController
    */
    global testmethod static void testCommunitiesSelfRegConfirmController() {
        // Instantiate a new controller with all parameters in the page
        CommunitiesSelfRegConfirmController controller = new CommunitiesSelfRegConfirmController(); 
    }


}