/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_APXT_Redlining_Managed_ClauseTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_APXT_Redlining_Managed_Cla5kTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new APXT_Redlining__Managed_Clause__c());
    }
}